/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as LayaRouteImport } from './routes/laya'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QIdRouteImport } from './routes/q.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const LayaRoute = LayaRouteImport.update({
  id: '/laya',
  path: '/laya',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QIdRoute = QIdRouteImport.update({
  id: '/q/$id',
  path: '/q/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/laya': typeof LayaRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/q/$id': typeof QIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/laya': typeof LayaRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/q/$id': typeof QIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/laya': typeof LayaRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/q/$id': typeof QIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ask' | '/laya' | '/login' | '/profile' | '/q/$id' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ask' | '/laya' | '/login' | '/profile' | '/q/$id' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/laya'
    | '/login'
    | '/profile'
    | '/q/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  LayaRoute: typeof LayaRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  QIdRoute: typeof QIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laya': {
      id: '/laya'
      path: '/laya'
      fullPath: '/laya'
      preLoaderRoute: typeof LayaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$id': {
      id: '/q/$id'
      path: '/q/$id'
      fullPath: '/q/$id'
      preLoaderRoute: typeof QIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  LayaRoute: LayaRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  QIdRoute: QIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
